Cache the image layers so the digests only get committed once
2019/09/11 15:59:03 MANIFEST-PROFILING start
2019/09/11 15:59:03 MANIFEST-PROFILING RawConfigFile
2019/09/11 15:59:03 MANIFEST-PROFILING cfgHash
2019/09/11 15:59:03 MANIFEST-PROFILING Layers
2019/09/11 15:59:03 MANIFEST-PROFILING filled descriptors
2019/09/11 15:59:03 PUT /v2/test/image/manifests/tag
2019/09/11 15:59:03 MANIFEST-PROFILING start
2019/09/11 15:59:03 WRITE-PROFILING committed
--- FAIL: TestPerf (36.32s)
    write_test.go:1259: time: 36.314556402s

Now we're down to 36 seconds - this looks pretty good