Profiling uploadOne, there is some peculiar time distribution
2019/09/11 11:55:57 WRITE-PROFILING Write start
2019/09/11 11:55:57 WRITE-PROFILING pulled layers
2019/09/11 11:55:57 WRITE-PROFILING made options
2019/09/11 11:55:57 WRITE-PROFILING created writer
2019/09/11 11:56:06 WRITE-PROFILING done parallel computing digests
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:006641632718d88f91d7104b7fb73a0a51983bf4745064a05fb17cef08b9c484: 25.271µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:c8e59f11a9adb71a018b9c3181c1d1037ff502d97937b4d4c196517a25ee23ea: 20.235µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:56c1cab9a21ab143544fca5b24abbf1b377edd5396d27d0a42f1b5d9899c7bda: 16.998µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:633638cc12386f9ce64e337aa64feb6f403d1794faea8cef1159bc66644b3830: 8.048µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:da4412f2af4d9b08a7177d55ab649d9908486f71ea02dfd5e40ccb3820cae67a: 8.355µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:ef869d53b9981a8374813b01764292f0302b056ac38c4b62d197d865065ec607: 5.648µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:481b2c064d3cae8012d4a78ae35d7771f729b02eba32e306bc4057534552d2b7: 21.606µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:fd862fd9cdee525ba48148bb749d33bd50a545ba2be8dd080e7425117d5fe47c: 6.016µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:d5af1d234e50b043f6dfe9859f9e46bbaa34163c742e1ff6ddda626eee8d1331: 7.279µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:a2650247b5cb56138bdfc8b12c5646f87b4f94b79e911413b57d9216b714e9fb: 5.918µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:4dd7cdc1f480b0b5494142027ebb812352d1959a56b2b74e105a587ba06a00fb: 5.771µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:f50724a8040f2a0e8af9cdc2072d0ba3bf6021aa3a49a7586da414e136072468: 5.505µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:1c21e3a1b98d5a7bde5c4d3ee77d1fd6022d5c89525ba8a4f9f561fe9613900b: 5.678µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:e2b6891c9e6b1053dfce96dc758122b433e09308b92c0d8e9e4e4f7528de5bc5: 4.991µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:f6c5ec4049e6e96fe1b89575d80979844ce55b645580cdc701582453f68a5bd4: 4.778µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:5126e156a78ed932e561054c5484d8ccbcee91f67e600cfa959ab155089455ac: 5.426µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:03895926db4d49c34c0c25f425f269feb67ac640df1a3e82d9dcd1592eb8348f: 6.268µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:0fbd64e1bea64e032bc54d9d8946e8c515f89cf38f7b3f2f20aa4cc5c799be61: 5µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:3fbee64400b6eaf26cd277beb8468025a391720528edf9461f1f34e10b88924e: 15.116µs
2019/09/11 11:56:06 UPLOAD-ONE-PROFILING time to get digest for sha256:2dc6074bf8b452bf7404088a7be1ca02c205352224a4054943fb5ba78d47a516: 7.333µs
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:ef869d53b9981a8374813b01764292f0302b056ac38c4b62d197d865065ec607
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:da4412f2af4d9b08a7177d55ab649d9908486f71ea02dfd5e40ccb3820cae67a
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:481b2c064d3cae8012d4a78ae35d7771f729b02eba32e306bc4057534552d2b7
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:006641632718d88f91d7104b7fb73a0a51983bf4745064a05fb17cef08b9c484
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:56c1cab9a21ab143544fca5b24abbf1b377edd5396d27d0a42f1b5d9899c7bda
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:56c1cab9a21ab143544fca5b24abbf1b377edd5396d27d0a42f1b5d9899c7bda
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:da4412f2af4d9b08a7177d55ab649d9908486f71ea02dfd5e40ccb3820cae67a
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:f6c5ec4049e6e96fe1b89575d80979844ce55b645580cdc701582453f68a5bd4
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:d5af1d234e50b043f6dfe9859f9e46bbaa34163c742e1ff6ddda626eee8d1331
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:f50724a8040f2a0e8af9cdc2072d0ba3bf6021aa3a49a7586da414e136072468
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:c8e59f11a9adb71a018b9c3181c1d1037ff502d97937b4d4c196517a25ee23ea
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:a2650247b5cb56138bdfc8b12c5646f87b4f94b79e911413b57d9216b714e9fb
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:ef869d53b9981a8374813b01764292f0302b056ac38c4b62d197d865065ec607
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:006641632718d88f91d7104b7fb73a0a51983bf4745064a05fb17cef08b9c484
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:1c21e3a1b98d5a7bde5c4d3ee77d1fd6022d5c89525ba8a4f9f561fe9613900b
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:fd862fd9cdee525ba48148bb749d33bd50a545ba2be8dd080e7425117d5fe47c
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:5126e156a78ed932e561054c5484d8ccbcee91f67e600cfa959ab155089455ac
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING streamed sha256:56c1cab9a21ab143544fca5b24abbf1b377edd5396d27d0a42f1b5d9899c7bda
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING again got digest sha256:56c1cab9a21ab143544fca5b24abbf1b377edd5396d27d0a42f1b5d9899c7bda
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:633638cc12386f9ce64e337aa64feb6f403d1794faea8cef1159bc66644b3830
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:2dc6074bf8b452bf7404088a7be1ca02c205352224a4054943fb5ba78d47a516
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:e2b6891c9e6b1053dfce96dc758122b433e09308b92c0d8e9e4e4f7528de5bc5
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:3fbee64400b6eaf26cd277beb8468025a391720528edf9461f1f34e10b88924e
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:0fbd64e1bea64e032bc54d9d8946e8c515f89cf38f7b3f2f20aa4cc5c799be61
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:4dd7cdc1f480b0b5494142027ebb812352d1959a56b2b74e105a587ba06a00fb
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:3fbee64400b6eaf26cd277beb8468025a391720528edf9461f1f34e10b88924e
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING upload initiated for sha256:03895926db4d49c34c0c25f425f269feb67ac640df1a3e82d9dcd1592eb8348f
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:a2650247b5cb56138bdfc8b12c5646f87b4f94b79e911413b57d9216b714e9fb
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:0fbd64e1bea64e032bc54d9d8946e8c515f89cf38f7b3f2f20aa4cc5c799be61
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:5126e156a78ed932e561054c5484d8ccbcee91f67e600cfa959ab155089455ac
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:c8e59f11a9adb71a018b9c3181c1d1037ff502d97937b4d4c196517a25ee23ea
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:481b2c064d3cae8012d4a78ae35d7771f729b02eba32e306bc4057534552d2b7
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:f6c5ec4049e6e96fe1b89575d80979844ce55b645580cdc701582453f68a5bd4
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:fd862fd9cdee525ba48148bb749d33bd50a545ba2be8dd080e7425117d5fe47c
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:03895926db4d49c34c0c25f425f269feb67ac640df1a3e82d9dcd1592eb8348f
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:2dc6074bf8b452bf7404088a7be1ca02c205352224a4054943fb5ba78d47a516
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:f50724a8040f2a0e8af9cdc2072d0ba3bf6021aa3a49a7586da414e136072468
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:633638cc12386f9ce64e337aa64feb6f403d1794faea8cef1159bc66644b3830
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:d5af1d234e50b043f6dfe9859f9e46bbaa34163c742e1ff6ddda626eee8d1331
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:e2b6891c9e6b1053dfce96dc758122b433e09308b92c0d8e9e4e4f7528de5bc5
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:1c21e3a1b98d5a7bde5c4d3ee77d1fd6022d5c89525ba8a4f9f561fe9613900b
2019/09/11 11:56:07 UPLOAD-ONE-PROFILING compressed for sha256:4dd7cdc1f480b0b5494142027ebb812352d1959a56b2b74e105a587ba06a00fb
2019/09/11 11:56:12 UPLOAD-ONE-PROFILING streamed sha256:da4412f2af4d9b08a7177d55ab649d9908486f71ea02dfd5e40ccb3820cae67a
2019/09/11 11:56:12 UPLOAD-ONE-PROFILING again got digest sha256:da4412f2af4d9b08a7177d55ab649d9908486f71ea02dfd5e40ccb3820cae67a
2019/09/11 11:56:13 UPLOAD-ONE-PROFILING streamed sha256:ef869d53b9981a8374813b01764292f0302b056ac38c4b62d197d865065ec607
2019/09/11 11:56:13 UPLOAD-ONE-PROFILING again got digest sha256:ef869d53b9981a8374813b01764292f0302b056ac38c4b62d197d865065ec607
2019/09/11 11:56:13 UPLOAD-ONE-PROFILING streamed sha256:006641632718d88f91d7104b7fb73a0a51983bf4745064a05fb17cef08b9c484
2019/09/11 11:56:13 UPLOAD-ONE-PROFILING again got digest sha256:006641632718d88f91d7104b7fb73a0a51983bf4745064a05fb17cef08b9c484
2019/09/11 11:56:14 UPLOAD-ONE-PROFILING committed sha256:56c1cab9a21ab143544fca5b24abbf1b377edd5396d27d0a42f1b5d9899c7bda
2019/09/11 11:56:14 UPLOAD-ONE-PROFILING streamed sha256:3fbee64400b6eaf26cd277beb8468025a391720528edf9461f1f34e10b88924e
2019/09/11 11:56:14 UPLOAD-ONE-PROFILING again got digest sha256:3fbee64400b6eaf26cd277beb8468025a391720528edf9461f1f34e10b88924e
2019/09/11 11:56:14 UPLOAD-ONE-PROFILING streamed sha256:a2650247b5cb56138bdfc8b12c5646f87b4f94b79e911413b57d9216b714e9fb
2019/09/11 11:56:14 UPLOAD-ONE-PROFILING again got digest sha256:a2650247b5cb56138bdfc8b12c5646f87b4f94b79e911413b57d9216b714e9fb
2019/09/11 11:56:15 UPLOAD-ONE-PROFILING streamed sha256:0fbd64e1bea64e032bc54d9d8946e8c515f89cf38f7b3f2f20aa4cc5c799be61
2019/09/11 11:56:15 UPLOAD-ONE-PROFILING again got digest sha256:0fbd64e1bea64e032bc54d9d8946e8c515f89cf38f7b3f2f20aa4cc5c799be61
2019/09/11 11:56:20 UPLOAD-ONE-PROFILING streamed sha256:c8e59f11a9adb71a018b9c3181c1d1037ff502d97937b4d4c196517a25ee23ea
2019/09/11 11:56:20 UPLOAD-ONE-PROFILING again got digest sha256:c8e59f11a9adb71a018b9c3181c1d1037ff502d97937b4d4c196517a25ee23ea
2019/09/11 11:56:21 UPLOAD-ONE-PROFILING streamed sha256:481b2c064d3cae8012d4a78ae35d7771f729b02eba32e306bc4057534552d2b7
2019/09/11 11:56:21 UPLOAD-ONE-PROFILING again got digest sha256:481b2c064d3cae8012d4a78ae35d7771f729b02eba32e306bc4057534552d2b7
2019/09/11 11:56:22 UPLOAD-ONE-PROFILING streamed sha256:fd862fd9cdee525ba48148bb749d33bd50a545ba2be8dd080e7425117d5fe47c
2019/09/11 11:56:22 UPLOAD-ONE-PROFILING again got digest sha256:fd862fd9cdee525ba48148bb749d33bd50a545ba2be8dd080e7425117d5fe47c
2019/09/11 11:56:22 UPLOAD-ONE-PROFILING streamed sha256:f6c5ec4049e6e96fe1b89575d80979844ce55b645580cdc701582453f68a5bd4
2019/09/11 11:56:22 UPLOAD-ONE-PROFILING again got digest sha256:f6c5ec4049e6e96fe1b89575d80979844ce55b645580cdc701582453f68a5bd4
2019/09/11 11:56:22 UPLOAD-ONE-PROFILING streamed sha256:5126e156a78ed932e561054c5484d8ccbcee91f67e600cfa959ab155089455ac
2019/09/11 11:56:22 UPLOAD-ONE-PROFILING again got digest sha256:5126e156a78ed932e561054c5484d8ccbcee91f67e600cfa959ab155089455ac
2019/09/11 11:56:23 UPLOAD-ONE-PROFILING streamed sha256:03895926db4d49c34c0c25f425f269feb67ac640df1a3e82d9dcd1592eb8348f
2019/09/11 11:56:23 UPLOAD-ONE-PROFILING again got digest sha256:03895926db4d49c34c0c25f425f269feb67ac640df1a3e82d9dcd1592eb8348f
2019/09/11 11:56:42 UPLOAD-ONE-PROFILING streamed sha256:2dc6074bf8b452bf7404088a7be1ca02c205352224a4054943fb5ba78d47a516
2019/09/11 11:56:42 UPLOAD-ONE-PROFILING again got digest sha256:2dc6074bf8b452bf7404088a7be1ca02c205352224a4054943fb5ba78d47a516
2019/09/11 11:56:42 UPLOAD-ONE-PROFILING streamed sha256:f50724a8040f2a0e8af9cdc2072d0ba3bf6021aa3a49a7586da414e136072468
2019/09/11 11:56:42 UPLOAD-ONE-PROFILING again got digest sha256:f50724a8040f2a0e8af9cdc2072d0ba3bf6021aa3a49a7586da414e136072468
2019/09/11 11:56:43 UPLOAD-ONE-PROFILING streamed sha256:633638cc12386f9ce64e337aa64feb6f403d1794faea8cef1159bc66644b3830
2019/09/11 11:56:43 UPLOAD-ONE-PROFILING again got digest sha256:633638cc12386f9ce64e337aa64feb6f403d1794faea8cef1159bc66644b3830
2019/09/11 11:56:43 UPLOAD-ONE-PROFILING streamed sha256:d5af1d234e50b043f6dfe9859f9e46bbaa34163c742e1ff6ddda626eee8d1331
2019/09/11 11:56:43 UPLOAD-ONE-PROFILING again got digest sha256:d5af1d234e50b043f6dfe9859f9e46bbaa34163c742e1ff6ddda626eee8d1331
2019/09/11 11:56:44 UPLOAD-ONE-PROFILING streamed sha256:e2b6891c9e6b1053dfce96dc758122b433e09308b92c0d8e9e4e4f7528de5bc5
2019/09/11 11:56:44 UPLOAD-ONE-PROFILING again got digest sha256:e2b6891c9e6b1053dfce96dc758122b433e09308b92c0d8e9e4e4f7528de5bc5
2019/09/11 11:56:44 UPLOAD-ONE-PROFILING streamed sha256:1c21e3a1b98d5a7bde5c4d3ee77d1fd6022d5c89525ba8a4f9f561fe9613900b
2019/09/11 11:56:44 UPLOAD-ONE-PROFILING again got digest sha256:1c21e3a1b98d5a7bde5c4d3ee77d1fd6022d5c89525ba8a4f9f561fe9613900b
2019/09/11 11:56:47 UPLOAD-ONE-PROFILING streamed sha256:4dd7cdc1f480b0b5494142027ebb812352d1959a56b2b74e105a587ba06a00fb
2019/09/11 11:56:47 UPLOAD-ONE-PROFILING again got digest sha256:4dd7cdc1f480b0b5494142027ebb812352d1959a56b2b74e105a587ba06a00fb
2019/09/11 11:56:47 UPLOAD-ONE-PROFILING committed sha256:da4412f2af4d9b08a7177d55ab649d9908486f71ea02dfd5e40ccb3820cae67a
2019/09/11 11:56:47 UPLOAD-ONE-PROFILING committed sha256:ef869d53b9981a8374813b01764292f0302b056ac38c4b62d197d865065ec607
2019/09/11 11:56:47 UPLOAD-ONE-PROFILING committed sha256:006641632718d88f91d7104b7fb73a0a51983bf4745064a05fb17cef08b9c484
2019/09/11 11:56:47 UPLOAD-ONE-PROFILING committed sha256:3fbee64400b6eaf26cd277beb8468025a391720528edf9461f1f34e10b88924e
2019/09/11 11:56:47 UPLOAD-ONE-PROFILING committed sha256:a2650247b5cb56138bdfc8b12c5646f87b4f94b79e911413b57d9216b714e9fb
2019/09/11 11:56:48 UPLOAD-ONE-PROFILING committed sha256:0fbd64e1bea64e032bc54d9d8946e8c515f89cf38f7b3f2f20aa4cc5c799be61
2019/09/11 11:56:48 UPLOAD-ONE-PROFILING committed sha256:c8e59f11a9adb71a018b9c3181c1d1037ff502d97937b4d4c196517a25ee23ea
2019/09/11 11:56:48 UPLOAD-ONE-PROFILING committed sha256:481b2c064d3cae8012d4a78ae35d7771f729b02eba32e306bc4057534552d2b7
2019/09/11 11:56:48 UPLOAD-ONE-PROFILING committed sha256:fd862fd9cdee525ba48148bb749d33bd50a545ba2be8dd080e7425117d5fe47c
2019/09/11 11:56:48 UPLOAD-ONE-PROFILING committed sha256:f6c5ec4049e6e96fe1b89575d80979844ce55b645580cdc701582453f68a5bd4
2019/09/11 11:56:48 UPLOAD-ONE-PROFILING committed sha256:5126e156a78ed932e561054c5484d8ccbcee91f67e600cfa959ab155089455ac
2019/09/11 11:56:48 UPLOAD-ONE-PROFILING committed sha256:03895926db4d49c34c0c25f425f269feb67ac640df1a3e82d9dcd1592eb8348f
2019/09/11 11:56:49 UPLOAD-ONE-PROFILING committed sha256:2dc6074bf8b452bf7404088a7be1ca02c205352224a4054943fb5ba78d47a516
2019/09/11 11:56:49 UPLOAD-ONE-PROFILING committed sha256:f50724a8040f2a0e8af9cdc2072d0ba3bf6021aa3a49a7586da414e136072468
2019/09/11 11:56:49 UPLOAD-ONE-PROFILING committed sha256:633638cc12386f9ce64e337aa64feb6f403d1794faea8cef1159bc66644b3830
2019/09/11 11:56:49 UPLOAD-ONE-PROFILING committed sha256:d5af1d234e50b043f6dfe9859f9e46bbaa34163c742e1ff6ddda626eee8d1331
2019/09/11 11:56:49 UPLOAD-ONE-PROFILING committed sha256:e2b6891c9e6b1053dfce96dc758122b433e09308b92c0d8e9e4e4f7528de5bc5
2019/09/11 11:56:49 UPLOAD-ONE-PROFILING committed sha256:1c21e3a1b98d5a7bde5c4d3ee77d1fd6022d5c89525ba8a4f9f561fe9613900b
2019/09/11 11:56:49 UPLOAD-ONE-PROFILING committed sha256:4dd7cdc1f480b0b5494142027ebb812352d1959a56b2b74e105a587ba06a00fb
2019/09/11 11:56:49 WRITE-PROFILING done waiting for layers + config
2019/09/11 11:57:06 WRITE-PROFILING committed
--- FAIL: TestPerf (69.38s)
    write_test.go:1259: time: 1m9.376608216s

I picked some random shas to trace through:
Following 481b2c064d3cae8012d4a78ae35d7771f729b02eba32e306bc4057534552d2b7:
1) 14 seconds spent streaming, 11:56:07 to 11:56:21
2) 27 seconds spent committing, 11:56:21 to 11:56:48

Following f50724a8040f2a0e8af9cdc2072d0ba3bf6021aa3a49a7586da414e136072468:
1) 35 seconds spent streaming, 11:56:07 to 11:56:42
2) 7 seconds spent committing, 11:56:42 to 11:56:49

Following 5126e156a78ed932e561054c5484d8ccbcee91f67e600cfa959ab155089455ac:
1) 15 seconds spent streaming, 11:56:07 to 11:56:22
2) 26 seconds spent committing, 11:56:22 to 11:56:48

Following 1c21e3a1b98d5a7bde5c4d3ee77d1fd6022d5c89525ba8a4f9f561fe9613900b:
1) 37 seconds spent streaming, 11:56:07 to 11:56:44
2) 5 seconds spent committing, 11:56:44 to 11:56:49

Since these timestamps are whack I ran some real analysis (all timestamps in seconds):
time to streamed: 14.0
time to streamed: 37.0
time to streamed: 7.0
time to streamed: 35.0
time to streamed: 15.0
time to streamed: 6.0
time to streamed: 15.0
time to streamed: 16.0
time to streamed: 7.0
time to streamed: 15.0
time to streamed: 5.0
time to streamed: 40.0
time to streamed: 0.0
time to streamed: 6.0
time to streamed: 37.0
time to streamed: 36.0
time to streamed: 35.0
time to streamed: 13.0
time to streamed: 36.0
time to streamed: 8.0
time to committed: 27.0
time to committed: 5.0
time to committed: 33.0
time to committed: 7.0
time to committed: 26.0
time to committed: 34.0
time to committed: 26.0
time to committed: 25.0
time to committed: 33.0
time to committed: 26.0
time to committed: 35.0
time to committed: 2.0
time to committed: 7.0
time to committed: 34.0
time to committed: 5.0
time to committed: 6.0
time to committed: 7.0
time to committed: 28.0
time to committed: 6.0
time to committed: 33.0
total: 41.0
total: 42.0
total: 40.0
total: 42.0
total: 41.0
total: 40.0
total: 41.0
total: 41.0
total: 40.0
total: 41.0
total: 40.0
total: 42.0
total: 7.0
total: 40.0
total: 42.0
total: 42.0
total: 42.0
total: 41.0
total: 42.0
total: 41.0

What we notice here is that either streaming or committing take a long time, but the totals are always the same.

Looking at https://github.com/google/go-containerregistry/blob/8b1ae43a6dc3b266d2f46cf6b207dd14abc6711a/pkg/registry/blobs.go, this actually makes a lot of sense. Most of the time is spent waiting for locks, because the server holds locks while the client is compressing. In the next commit, I'll try compressing first, and then send the compressed blob.