Switch to read from os.Stdin, fails and I don't know why
    ./crane export - ubuntu.tar < test.tar
    Error: reading tarball from stdin: archive/tar: invalid tar header