crane export: Support reading tarball from a stream (#1274)
* crane export: Read tarball from a file

A working concept that reads the image from "test.tar" if first
argument is specified as "-".

The goal is to read from a stdin, but that part (commented) fails with

    Error: reading tarball from stdin: archive/tar: invalid tar header

* Switch to read from os.Stdin, fails and I don't know why

    ./crane export - ubuntu.tar < test.tar
    Error: reading tarball from stdin: archive/tar: invalid tar header

* Create temporary file if input is read from stdin

* Update docs

* Document `export` output can also be stdout

Co-authored-by: Jason Hall <jasonhall@redhat.com>

* export: Remove debug info about found layers

* Update presubmit docs

Co-authored-by: Jason Hall <jasonhall@redhat.com>